/**
 * LaTeX Performance Configuration - cache.config.js
 * Auto-generated by LaTeX Performance Optimizer
 * Generated: 2025-09-08T15:26:05.606Z
 */

module.exports = {
  "enableCaching": true,
  "cacheDir": "/Users/sac/unjucks/.latex-cache",
  "maxSize": 524288000,
  "maxAge": 604800000,
  "strategy": "intelligent",
  "enableCompression": true,
  "compressionLevel": 6,
  "writeBehind": true,
  "batchWrites": true
};
