/**
 * LaTeX Performance Configuration - memory.config.js
 * Auto-generated by LaTeX Performance Optimizer
 * Generated: 2025-09-08T15:26:05.607Z
 */

module.exports = {
  "enableMemoryMonitoring": true,
  "memoryPressureThreshold": 0.8,
  "enableAggressiveCleanup": true,
  "gcInterval": 30000,
  "memoryLimit": 30923764531,
  "enableMemoryLeakDetection": true
};
