/**
 * LaTeX Performance Configuration - monitoring.config.js
 * Auto-generated by LaTeX Performance Optimizer
 * Generated: 2025-09-08T15:26:05.608Z
 */

export default {
  "enableRealTimeMonitoring": true,
  "metricsInterval": 5000,
  "enableBottleneckDetection": true,
  "enablePerformanceAlerts": true,
  "generateReports": true,
  "reportInterval": 300000,
  "outputDir": "./performance-reports"
};
