/**
 * LaTeX Performance Configuration - parallel.config.js
 * Auto-generated by LaTeX Performance Optimizer
 * Generated: 2025-09-08T15:26:05.607Z
 */

export default {
  "enableParallelCompilation": true,
  "maxWorkers": 8,
  "workerTimeout": 300000,
  "enableLoadBalancing": true,
  "queueStrategy": "priority",
  "enableAdaptiveScaling": true
};
