/**
 * LaTeX Performance Configuration - streaming.config.js
 * Auto-generated by LaTeX Performance Optimizer
 * Generated: 2025-09-08T15:26:05.608Z
 */

module.exports = {
  "enableStreaming": true,
  "chunkSize": 131072,
  "maxMemoryUsage": 134217728,
  "chunkingStrategy": "smart",
  "enableLazyLoading": true,
  "enableProgressiveCompilation": true
};
