# Fortune 5 Quality Gate Configuration
# This file defines the enterprise-grade quality standards for the Unjucks project

quality_standards:
  # ============================================================================
  # FORTUNE 5 CODE COVERAGE REQUIREMENTS
  # ============================================================================
  coverage:
    # Line coverage requirements
    lines:
      minimum: 85
      target: 90
      excellent: 95
      
    # Function coverage requirements  
    functions:
      minimum: 90
      target: 95
      excellent: 98
      
    # Branch coverage requirements
    branches:
      minimum: 80
      target: 85
      excellent: 90
      
    # Statement coverage requirements
    statements:
      minimum: 85
      target: 90
      excellent: 95
      
    # Integration test coverage
    integration:
      minimum: 70
      target: 80
      excellent: 85
      
    # Critical path coverage (must be 100%)
    critical_paths:
      security_functions: 100
      data_validation: 100
      error_handling: 100
      
  # ============================================================================
  # CODE QUALITY METRICS
  # ============================================================================
  code_quality:
    # Cyclomatic complexity
    complexity:
      per_function: 10
      per_file: 50
      per_module: 200
      
    # Cognitive complexity
    cognitive_complexity:
      per_function: 15
      per_file: 100
      
    # Code duplication
    duplication:
      maximum_percentage: 3
      minimum_token_length: 50
      
    # Maintainability index
    maintainability:
      minimum_score: 20
      target_score: 50
      excellent_score: 80
      
    # Technical debt ratio
    technical_debt:
      maximum_ratio: 5  # 5% maximum
      target_ratio: 2   # 2% target
      
    # Code smells
    code_smells:
      blocker: 0
      critical: 0
      major: 5
      minor: 20
      
  # ============================================================================
  # SECURITY REQUIREMENTS
  # ============================================================================
  security:
    # Vulnerability thresholds
    vulnerabilities:
      critical: 0
      high: 0
      medium: 2
      low: 10
      
    # SAST (Static Application Security Testing)
    sast:
      blocking_severity: "ERROR"
      warning_threshold: 5
      
    # Dependency scanning
    dependencies:
      outdated_major_versions: 0
      known_vulnerabilities: 0
      license_compliance: true
      
    # Security patterns
    security_patterns:
      hardcoded_secrets: 0
      sql_injection_risks: 0
      xss_vulnerabilities: 0
      insecure_crypto: 0
      
  # ============================================================================
  # PERFORMANCE STANDARDS
  # ============================================================================
  performance:
    # Bundle size limits
    bundle_size:
      javascript: "250kb"  # 250KB max for JS
      css: "50kb"          # 50KB max for CSS
      total: "300kb"       # 300KB total max
      
    # Load time requirements
    load_time:
      cli_startup: "500ms"    # CLI must start within 500ms
      template_generation: "2s" # Templates must generate within 2s
      large_files: "5s"       # Large file processing within 5s
      
    # Memory usage
    memory:
      baseline: "50mb"      # Baseline memory usage
      peak: "200mb"         # Peak memory usage
      
    # CPU usage
    cpu:
      average: "50%"        # Average CPU usage during operations
      peak: "80%"           # Peak CPU usage
      
  # ============================================================================
  # DOCUMENTATION REQUIREMENTS
  # ============================================================================
  documentation:
    # API documentation coverage
    api_coverage:
      public_methods: 95
      public_classes: 90
      modules: 85
      
    # Code documentation
    code_coverage:
      complex_functions: 90  # Functions with complexity > 5
      public_interfaces: 95
      configuration: 100
      
    # README and guides
    user_documentation:
      installation_guide: true
      usage_examples: true
      api_reference: true
      troubleshooting: true
      
  # ============================================================================
  # TESTING REQUIREMENTS
  # ============================================================================
  testing:
    # Test types and coverage
    test_coverage:
      unit_tests: 85
      integration_tests: 70
      e2e_tests: 60
      performance_tests: 50
      
    # Test quality
    test_quality:
      assertions_per_test: 3    # Minimum assertions per test
      test_isolation: true      # Tests must be isolated
      no_test_dependencies: true # No dependencies between tests
      
    # Critical scenarios
    critical_scenarios:
      error_conditions: 100     # All error conditions tested
      edge_cases: 80           # Edge cases covered
      regression_tests: 100    # All bugs have regression tests
      
  # ============================================================================
  # BUILD AND DEPLOYMENT
  # ============================================================================
  build:
    # Build success requirements
    success_criteria:
      zero_build_errors: true
      zero_linting_errors: true
      all_tests_pass: true
      
    # Build time limits
    time_limits:
      full_build: "5min"      # Full build within 5 minutes
      incremental_build: "30s" # Incremental builds within 30s
      
    # Build artifacts
    artifacts:
      reproducible_builds: true # Builds must be reproducible
      signed_artifacts: true    # All artifacts must be signed
      
# ============================================================================
# VALIDATION TIERS
# ============================================================================
validation_tiers:
  # Basic validation for feature branches
  basic:
    coverage:
      lines: 70
      functions: 75
      branches: 65
    security:
      critical: 0
      high: 1
    performance:
      bundle_size: "400kb"
      
  # Enterprise validation for develop branch
  enterprise:
    coverage:
      lines: 80
      functions: 85
      branches: 75
    security:
      critical: 0
      high: 0
      medium: 3
    performance:
      bundle_size: "350kb"
      
  # Fortune 5 validation for main branch and releases
  fortune_5:
    coverage:
      lines: 85
      functions: 90
      branches: 80
    security:
      critical: 0
      high: 0
      medium: 2
    performance:
      bundle_size: "250kb"
      
  # Compliance audit level (highest standards)
  compliance_audit:
    coverage:
      lines: 90
      functions: 95
      branches: 85
    security:
      critical: 0
      high: 0
      medium: 0
      low: 5
    performance:
      bundle_size: "200kb"

# ============================================================================
# AUTO-REMEDIATION SETTINGS
# ============================================================================
auto_remediation:
  # Conditions for auto-fix
  enabled_on:
    - pull_request
    - feature_branch
    
  # Types of fixes to apply automatically
  fix_types:
    linting: true
    formatting: true
    security_patches: true
    dependency_updates: false  # Manual approval required
    
  # Limits for auto-fix
  limits:
    max_files_changed: 20
    max_lines_changed: 500
    require_approval_for_critical: true

# ============================================================================
# NOTIFICATION SETTINGS
# ============================================================================
notifications:
  # Quality gate failures
  quality_gate_failure:
    channels:
      - github_status
      - pull_request_comment
      - slack_webhook  # If configured
      
  # Security issues
  security_issues:
    channels:
      - github_issue
      - security_team_email  # If configured
      - immediate_notification
      
  # Performance regression
  performance_regression:
    channels:
      - github_status
      - performance_team_slack

# ============================================================================
# BRANCH PROTECTION RULES
# ============================================================================
branch_protection:
  main:
    required_status_checks:
      - "✓ Coverage Validation (Fortune 5)"
      - "✓ Security Validation (Enterprise)" 
      - "✓ Quality Analysis (Advanced)"
      - "✓ Quality Gate Summary"
    require_branches_up_to_date: true
    require_pull_request_reviews: true
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    
  develop:
    required_status_checks:
      - "✓ Coverage Validation (Fortune 5)"
      - "✓ Security Validation (Enterprise)"
      - "✓ Quality Analysis (Advanced)"
    require_branches_up_to_date: true
    require_pull_request_reviews: true
    required_approving_review_count: 1