name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature you'd like to see
      placeholder: Brief summary of the feature...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Template Engine Enhancement
        - New CLI Command
        - Export Format Support
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Testing
        - Build System
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        A clear and concise description of any alternative solutions
        or features you've considered.

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a developer, I want to...
        2. When working with templates, I need to...
        3. For my project, it would be helpful if...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```bash
        # Example command
        unjucks generate mytemplate --new-option
        ```
        
        ```njk
        <!-- Example template usage -->
        {{ someNewFilter() }}
        ```

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my work
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to test this feature
        - label: I would be willing to write documentation
        - label: I would be willing to review the implementation

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce any breaking changes?
      placeholder: |
        Consider if this feature would:
        - Change existing CLI behavior
        - Modify template syntax
        - Alter output formats
        - Require configuration changes

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small addition or modification
        - Moderate - Requires some design and implementation
        - Complex - Significant design and implementation work
        - Major - Large feature requiring architectural changes
        - Unknown

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: |
        - Links to similar features in other tools
        - Mockups or diagrams
        - Related issues or discussions
        - Any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have provided clear use cases and examples
          required: true
        - label: I understand this is a request, not a guarantee
          required: true