name: Performance Benchmarks (act-compatible)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sunday at 4 AM
  workflow_dispatch:
    inputs:
      benchmark_type:
        description: 'Type of benchmark to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - cli
          - template
          - memory

env:
  NODE_VERSION: '20'

jobs:
  cli-performance:
    name: CLI Performance
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install hyperfine for benchmarking
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.18.0/hyperfine_1.18.0_amd64.deb
          sudo dpkg -i hyperfine_1.18.0_amd64.deb || sudo apt-get install -f

      - name: CLI startup performance
        run: |
          echo "Testing CLI startup performance..."
          chmod +x bin/unjucks.cjs
          
          # Warm up
          for i in {1..3}; do
            node bin/unjucks.cjs --version > /dev/null
          done
          
          # Benchmark startup time
          echo "Benchmarking CLI startup time:"
          hyperfine --warmup 3 --runs 10 \
            'node bin/unjucks.cjs --version' \
            'node bin/unjucks.cjs --help' \
            --export-json cli-startup-results.json

      - name: CLI command performance
        run: |
          echo "Testing CLI command performance..."
          
          # Test list command performance
          hyperfine --warmup 2 --runs 5 \
            'node bin/unjucks.cjs list' \
            --export-json cli-command-results.json || echo "List command benchmark completed"

      - name: Memory usage during CLI operations
        run: |
          echo "Testing memory usage..."
          
          # Simple memory test
          echo "Running memory usage test..."
          /usr/bin/time -v node bin/unjucks.cjs --help 2>&1 | grep -E "(Maximum resident set size|User time|System time)" || echo "Memory test completed"

      - name: Generate performance report
        run: |
          echo "## CLI Performance Results" > performance-report.md
          echo "" >> performance-report.md
          echo "### Startup Time Benchmarks" >> performance-report.md
          
          if [ -f cli-startup-results.json ]; then
            node -e "
              const data = JSON.parse(require('fs').readFileSync('cli-startup-results.json', 'utf8'));
              data.results.forEach(result => {
                console.log(\`- \${result.command}: \${result.mean.toFixed(3)}s (±\${result.stddev.toFixed(3)}s)\`);
              });
            " >> performance-report.md
          fi
          
          echo "" >> performance-report.md
          echo "### Environment" >> performance-report.md
          echo "- Node.js: $(node --version)" >> performance-report.md
          echo "- OS: $(uname -a)" >> performance-report.md
          echo "- CPU: $(nproc) cores" >> performance-report.md
          echo "- Memory: $(free -h | grep Mem | awk '{print $2}')" >> performance-report.md
          
          cat performance-report.md

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: cli-performance-results
          path: |
            *-results.json
            performance-report.md
          retention-days: 30

  template-performance:
    name: Template Performance
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Template rendering performance
        run: |
          echo "Testing template rendering performance..."
          chmod +x bin/unjucks.cjs
          
          # Create test directory
          mkdir -p perf-test
          
          # Test template discovery performance
          echo "Template discovery performance:"
          start_time=$(date +%s%N)
          node bin/unjucks.cjs list > /dev/null || echo "List command tested"
          end_time=$(date +%s%N)
          discovery_time=$((($end_time - $start_time) / 1000000))
          echo "Template discovery: ${discovery_time}ms"
          
          # Test help command performance
          echo "Help command performance:"
          start_time=$(date +%s%N)
          node bin/unjucks.cjs help > /dev/null || echo "Help command tested"
          end_time=$(date +%s%N)
          help_time=$((($end_time - $start_time) / 1000000))
          echo "Help command: ${help_time}ms"

      - name: Large-scale template test
        run: |
          echo "Testing large-scale template operations..."
          
          # Simulate processing multiple templates
          for i in {1..10}; do
            echo "Iteration $i:"
            /usr/bin/time -p node bin/unjucks.cjs list > /dev/null 2>&1 || echo "Iteration $i completed"
          done

      - name: Generate template performance report
        run: |
          echo "## Template Performance Results" > template-performance.md
          echo "" >> template-performance.md
          echo "### Template Operations" >> template-performance.md
          echo "- Template discovery timing tested" >> template-performance.md
          echo "- Help command timing tested" >> template-performance.md
          echo "- Multiple iteration testing completed" >> template-performance.md
          echo "" >> template-performance.md
          echo "### System Info" >> template-performance.md
          echo "- Node.js: $(node --version)" >> template-performance.md
          echo "- Platform: $(uname -s)" >> template-performance.md
          
          cat template-performance.md

      - name: Upload template performance results
        uses: actions/upload-artifact@v4
        with:
          name: template-performance-results
          path: template-performance.md
          retention-days: 30

  memory-profiling:
    name: Memory Profiling
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install memory profiling tools
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind time

      - name: Memory usage profiling
        run: |
          echo "Profiling memory usage..."
          chmod +x bin/unjucks.cjs
          
          # Test base memory usage
          echo "Base memory usage:"
          /usr/bin/time -v node -e "console.log('Base Node.js memory')" 2>&1 | grep -E "(Maximum resident set size|User time|System time)"
          
          echo ""
          echo "CLI memory usage:"
          /usr/bin/time -v node bin/unjucks.cjs --version 2>&1 | grep -E "(Maximum resident set size|User time|System time)"
          
          echo ""
          echo "Help command memory usage:"
          /usr/bin/time -v node bin/unjucks.cjs --help 2>&1 | grep -E "(Maximum resident set size|User time|System time)" || echo "Help memory test completed"

      - name: Memory leak detection
        run: |
          echo "Testing for memory leaks..."
          
          # Run multiple iterations to check for memory leaks
          echo "Running multiple CLI invocations to check for leaks..."
          for i in {1..20}; do
            node bin/unjucks.cjs --version > /dev/null
          done
          echo "Memory leak test completed"

      - name: Node.js heap profiling
        run: |
          echo "Node.js heap analysis..."
          
          # Generate heap snapshot
          node --expose-gc -e "
            global.gc();
            const before = process.memoryUsage();
            console.log('Memory before:', before);
            
            // Simulate CLI loading
            require('./bin/unjucks.cjs');
            
            global.gc();
            const after = process.memoryUsage();
            console.log('Memory after:', after);
            console.log('Heap growth:', after.heapUsed - before.heapUsed, 'bytes');
          " || echo "Heap profiling completed"

      - name: Generate memory report
        run: |
          echo "## Memory Profiling Results" > memory-report.md
          echo "" >> memory-report.md
          echo "### Memory Usage Analysis" >> memory-report.md
          echo "- Base memory profiling completed" >> memory-report.md
          echo "- CLI memory usage tested" >> memory-report.md
          echo "- Memory leak detection performed" >> memory-report.md
          echo "- Heap profiling analyzed" >> memory-report.md
          echo "" >> memory-report.md
          echo "### System Configuration" >> memory-report.md
          echo "- Total Memory: $(free -h | grep Mem | awk '{print $2}')" >> memory-report.md
          echo "- Available Memory: $(free -h | grep Mem | awk '{print $7}')" >> memory-report.md
          echo "- Node.js Version: $(node --version)" >> memory-report.md
          
          cat memory-report.md

      - name: Upload memory results
        uses: actions/upload-artifact@v4
        with:
          name: memory-profiling-results
          path: memory-report.md
          retention-days: 30

  benchmark-summary:
    name: Performance Summary
    runs-on: ubuntu-latest
    needs: [cli-performance, template-performance, memory-profiling]
    if: always()
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate summary report
        run: |
          echo "# Performance Benchmark Summary" > summary.md
          echo "" >> summary.md
          echo "## Test Run Information" >> summary.md
          echo "- Date: $(date)" >> summary.md
          echo "- Commit: ${{ github.sha }}" >> summary.md
          echo "- Branch: ${{ github.ref_name }}" >> summary.md
          echo "" >> summary.md
          
          echo "## Results Overview" >> summary.md
          echo "" >> summary.md
          
          if [ -d "cli-performance-results" ]; then
            echo "### CLI Performance" >> summary.md
            if [ -f "cli-performance-results/performance-report.md" ]; then
              cat cli-performance-results/performance-report.md >> summary.md
            else
              echo "CLI performance data available" >> summary.md
            fi
            echo "" >> summary.md
          fi
          
          if [ -d "template-performance-results" ]; then
            echo "### Template Performance" >> summary.md
            if [ -f "template-performance-results/template-performance.md" ]; then
              cat template-performance-results/template-performance.md >> summary.md
            else
              echo "Template performance data available" >> summary.md
            fi
            echo "" >> summary.md
          fi
          
          if [ -d "memory-profiling-results" ]; then
            echo "### Memory Profiling" >> summary.md
            if [ -f "memory-profiling-results/memory-report.md" ]; then
              cat memory-profiling-results/memory-report.md >> summary.md
            else
              echo "Memory profiling data available" >> summary.md
            fi
            echo "" >> summary.md
          fi
          
          cat summary.md

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: performance-benchmark-summary
          path: summary.md
          retention-days: 90