name: cli
description: Generate CLI applications
templates:
  - name: citty
    description: Citty CLI application
    files:
      - cli.ts
      - package.json
    prompts:
      - name: cliName
        message: "CLI name:"
        type: input
        default: my-cli
      - name: description
        message: "CLI description:"
        type: input
        default: A CLI tool built with Citty
