name: "React Component"
description: "A reusable React component with TypeScript support"
category: "starter"
complexity: "beginner"
tags: ["react", "typescript", "component", "frontend"]
author: "Unjucks Team"
version: "1.0.0"

variables:
  - name: componentName
    type: string
    description: "Name of the React component (PascalCase)"
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"
  
  - name: withProps
    type: boolean  
    description: "Include TypeScript props interface"
    default: true
  
  - name: withTests
    type: boolean
    description: "Generate test file"
    default: true
    
  - name: withStorybook
    type: boolean
    description: "Generate Storybook story"
    default: false
    
  - name: cssModule
    type: boolean
    description: "Use CSS modules for styling"
    default: false

  - name: description
    type: string
    description: "Component description for documentation"
    default: "A reusable React component"

examples:
  - "unjucks generate react-component Button --withProps --withTests"
  - "unjucks generate react-component Modal --withStorybook --cssModule"
  - "unjucks generate react-component Card --description 'Card component for displaying content'"

usage: |
  This template creates a complete React component with:
  - TypeScript interface for props
  - Proper JSX structure  
  - Optional test file with Jest/RTL
  - Optional Storybook story
  - Optional CSS module support