/**
 * New Component
 * Generated by Unjucks
 */

export class New {
  constructor() {
    this.name = 'new';
  }

  render() {
    return `<div class="new">${this.name}</div>`;
  }
}

export default New;