/**
 * TestFile Component
 * Generated by Unjucks
 */

export class TestFile {
  constructor() {
    this.name = 'TestFile';
  }

  render() {
    return `<div class="test-file">${this.name}</div>`;
  }
}

export default TestFile;