name: "REST API Endpoint"
description: "Production-ready REST API endpoint with validation, authentication, and comprehensive error handling"
category: "api"
complexity: "intermediate"
tags: ["api", "rest", "express", "nodejs", "validation", "authentication"]
author: "Unjucks Enterprise Team"
version: "1.0.0"

variables:
  - name: endpointName
    type: string
    description: "Name of the API endpoint (camelCase)"
    required: true
    pattern: "^[a-z][a-zA-Z0-9]*$"
  
  - name: resourceName
    type: string
    description: "Resource name (plural, lowercase)"
    required: true
    pattern: "^[a-z][a-z0-9]*$"
    
  - name: methods
    type: array
    description: "HTTP methods to implement"
    default: ["GET", "POST", "PUT", "DELETE"]
    choices: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
  
  - name: withValidation
    type: boolean
    description: "Include request validation with Joi schemas"
    default: true
    
  - name: withAuth
    type: boolean
    description: "Include JWT authentication middleware"
    default: true
    
  - name: withRBAC
    type: boolean
    description: "Include role-based access control"
    default: false
    
  - name: withPagination
    type: boolean
    description: "Include pagination for list endpoints"
    default: true
    
  - name: withFiltering
    type: boolean
    description: "Include query filtering and sorting"
    default: true
    
  - name: withRateLimit
    type: boolean
    description: "Include rate limiting per endpoint"
    default: true
    
  - name: withCaching
    type: boolean
    description: "Include Redis caching for GET requests"
    default: false
    
  - name: withAuditLog
    type: boolean
    description: "Include audit logging for compliance"
    default: true
    
  - name: apiVersion
    type: string
    description: "API version prefix"
    default: "v1"
    pattern: "^v[0-9]+$"
    
  - name: responseFormat
    type: string
    description: "Response format standard"
    default: "json-api"
    choices: ["json-api", "rest", "hal", "jsonld"]

examples:
  - "unjucks generate api endpoint --endpointName=users --resourceName=users --methods=GET,POST,PUT,DELETE"
  - "unjucks generate api endpoint --endpointName=products --withAuth --withRBAC --withCaching"
  - "unjucks generate api endpoint --endpointName=orders --withPagination --withFiltering --apiVersion=v2"

usage: |
  This template creates a complete REST API endpoint with:
  - Express.js route handlers for all specified HTTP methods
  - Comprehensive request validation using Joi schemas
  - JWT authentication and optional RBAC authorization
  - Standardized error handling and response formatting
  - Rate limiting and security middleware
  - Pagination, filtering, and sorting capabilities
  - Optional Redis caching for performance
  - Audit logging for compliance tracking
  - OpenAPI/Swagger documentation
  - Comprehensive unit and integration tests