// App configuration for {{ projectName | titleCase }}
// Generated by Unjucks Interview Copilot template

export default defineAppConfig({
  {% if withUI %}
  // Nuxt UI Theme Configuration
  ui: {
    colors: {
      primary: 'blue',
      secondary: 'indigo', 
      neutral: 'slate',
      success: 'green',
      warning: 'amber',
      error: 'red'
    },
    
    // Global UI component styling
    strategy: 'merge',
    
    // Custom component variants
    button: {
      slots: {
        base: 'focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 flex-shrink-0',
        loading: 'animate-spin'
      },
      variants: {
        color: {
          primary: {
            solid: 'shadow-sm ring-1 ring-inset ring-primary-500 text-white bg-primary-500 hover:bg-primary-600 disabled:bg-primary-500 focus-visible:ring-2 focus-visible:ring-primary-500'
          }
        }
      }
    },
    
    // Card component styling
    card: {
      slots: {
        base: 'overflow-hidden',
        header: 'flex items-center justify-between px-4 py-5 sm:px-6',
        body: 'px-4 py-5 sm:p-6',
        footer: 'flex items-center justify-between px-4 py-4 sm:px-6'
      },
      variants: {
        rounded: {
          none: '',
          sm: 'rounded-sm',
          DEFAULT: 'rounded-md',
          md: 'rounded-md',
          lg: 'rounded-lg',
          xl: 'rounded-xl',
          '2xl': 'rounded-2xl',
          '3xl': 'rounded-3xl',
          full: 'rounded-full'
        }
      }
    },
    
    // Modal/Dialog styling
    modal: {
      slots: {
        base: 'relative w-full flex flex-col',
        overlay: 'fixed inset-0 transition-opacity',
        background: 'absolute inset-0 bg-gray-200/75 dark:bg-gray-800/75',
        wrapper: 'fixed inset-0 z-50 flex justify-center overflow-y-auto',
        container: 'flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0'
      }
    }
  },
  {% endif %}

  // Application-specific configuration
  app: {
    name: '{{ projectName | titleCase }}',
    description: 'AI-powered mock interview simulator for technical and behavioral interviews',
    version: '1.0.0',
    
    // Branding
    logo: {
      light: '/logo-light.svg',
      dark: '/logo-dark.svg',
      alt: '{{ projectName | titleCase }} Logo',
      width: 120,
      height: 40
    },
    
    // Navigation
    navigation: {
      primary: [
        {
          label: 'Dashboard',
          icon: 'i-heroicons-home',
          to: '/dashboard',
          description: 'View your interview progress and statistics'
        },
        {
          label: 'Practice',
          icon: 'i-heroicons-play-circle',
          to: '/practice',
          description: 'Start a new mock interview session'
        },
        {
          label: 'History',
          icon: 'i-heroicons-clock',
          to: '/history',
          description: 'Review past interview sessions'
        },
        {
          label: 'Analytics',
          icon: 'i-heroicons-chart-bar-square',
          to: '/analytics',
          description: 'Detailed performance analytics'
        }
      ],
      
      secondary: [
        {
          label: 'Settings',
          icon: 'i-heroicons-cog-6-tooth',
          to: '/settings',
          description: 'Manage your account and preferences'
        },
        {
          label: 'Help',
          icon: 'i-heroicons-question-mark-circle',
          to: '/help',
          description: 'Get help and support'
        }
      ],
      
      footer: [
        {
          label: 'Privacy Policy',
          to: '/privacy',
          external: false
        },
        {
          label: 'Terms of Service',
          to: '/terms',
          external: false
        },
        {
          label: 'Contact',
          to: '/contact',
          external: false
        }
      ]
    }
  },

  // Interview-specific configuration
  interview: {
    // Available interview types
    types: [
      {
        id: 'technical',
        label: 'Technical Interview',
        description: 'Coding challenges, algorithms, and system design',
        icon: 'i-heroicons-code-bracket',
        color: 'blue',
        duration: { min: 30, max: 120, default: 60 },
        difficulties: ['easy', 'medium', 'hard']
      },
      {
        id: 'behavioral',
        label: 'Behavioral Interview', 
        description: 'Communication skills, team dynamics, and experience',
        icon: 'i-heroicons-chat-bubble-left-right',
        color: 'green',
        duration: { min: 20, max: 60, default: 45 },
        difficulties: ['easy', 'medium', 'hard']
      },
      {
        id: 'system-design',
        label: 'System Design',
        description: 'Architecture, scalability, and system thinking',
        icon: 'i-heroicons-squares-2x2',
        color: 'purple',
        duration: { min: 45, max: 120, default: 90 },
        difficulties: ['medium', 'hard']
      },
      {
        id: 'case-study',
        label: 'Case Study',
        description: 'Business problems and analytical thinking',
        icon: 'i-heroicons-briefcase',
        color: 'amber',
        duration: { min: 30, max: 90, default: 60 },
        difficulties: ['easy', 'medium', 'hard']
      }
    ],
    
    // Difficulty levels
    difficulties: {
      easy: {
        label: 'Easy',
        description: 'Entry level, basic concepts',
        color: 'green',
        icon: 'i-heroicons-star'
      },
      medium: {
        label: 'Medium', 
        description: 'Intermediate level, practical experience',
        color: 'yellow',
        icon: 'i-heroicons-star'
      },
      hard: {
        label: 'Hard',
        description: 'Advanced level, expert knowledge',
        color: 'red', 
        icon: 'i-heroicons-star'
      }
    },
    
    // Scoring system
    scoring: {
      maxScore: 100,
      passingScore: 70,
      categories: [
        {
          id: 'correctness',
          label: 'Correctness',
          weight: 30,
          description: 'Accuracy of the solution'
        },
        {
          id: 'approach',
          label: 'Approach',
          weight: 25,
          description: 'Problem-solving methodology'
        },
        {
          id: 'communication',
          label: 'Communication',
          weight: 20,
          description: 'Clarity of explanation'
        },
        {
          id: 'code-quality',
          label: 'Code Quality',
          weight: 15,
          description: 'Clean, readable code'
        },
        {
          id: 'efficiency',
          label: 'Efficiency',
          weight: 10,
          description: 'Time and space complexity'
        }
      ]
    },
    
    // AI Configuration
    ai: {
      models: {
        primary: 'gpt-4',
        fallback: 'gpt-3.5-turbo',
        alternatives: ['claude-3', 'gemini-pro']
      },
      
      settings: {
        temperature: 0.7,
        maxTokens: 2000,
        streaming: true,
        contextWindow: 4000
      },
      
      prompts: {
        interviewer: {
          system: 'You are an experienced technical interviewer conducting a mock interview. Be professional, encouraging, and provide constructive feedback.',
          personality: 'professional-friendly'
        },
        
        evaluator: {
          system: 'You are an expert code reviewer and interview evaluator. Provide detailed, constructive feedback on interview responses.',
          criteria: ['correctness', 'approach', 'communication', 'code-quality', 'efficiency']
        }
      }
    }
  },

  // Theme and appearance
  theme: {
    dark: 'dark',
    light: 'light',
    system: 'system',
    default: 'system',
    
    // Custom CSS properties
    colors: {
      background: {
        light: '#ffffff',
        dark: '#0f172a'
      },
      
      surface: {
        light: '#f8fafc',
        dark: '#1e293b'
      },
      
      accent: {
        light: '#3b82f6',
        dark: '#60a5fa'
      }
    }
  },

  // Features and capabilities
  features: {
    // Core features
    aiInterviews: true,
    realTimeFeedback: true,
    codeExecution: true,
    multiLanguageSupport: true,
    
    // Advanced features (may require premium)
    videoRecording: false,
    voiceAnalysis: false,
    customRubrics: false,
    teamManagement: false,
    advancedAnalytics: false,
    
    // Experimental features
    multimodalInput: false,
    collaborativeInterviews: false,
    adaptiveDifficulty: true
  },

  // Social and external links
  social: {
    github: 'https://github.com/yourorg/{{ projectName | kebabCase }}',
    twitter: 'https://twitter.com/{{ projectName | kebabCase }}',
    linkedin: 'https://linkedin.com/company/{{ projectName | kebabCase }}',
    discord: 'https://discord.gg/{{ projectName | kebabCase }}',
    email: 'support@{{ projectName | kebabCase }}.com'
  },

  // Analytics and tracking
  analytics: {
    googleAnalytics: {
      enabled: !!process.env.GOOGLE_ANALYTICS_ID,
      id: process.env.GOOGLE_ANALYTICS_ID
    },
    
    posthog: {
      enabled: !!process.env.POSTHOG_KEY,
      key: process.env.POSTHOG_KEY
    },
    
    // Custom events to track
    events: [
      'interview_started',
      'interview_completed',
      'question_answered',
      'feedback_received',
      'user_registered',
      'subscription_upgraded'
    ]
  },

  // SEO and meta configuration
  seo: {
    siteName: '{{ projectName | titleCase }}',
    titleSeparator: '•',
    description: 'Master technical and behavioral interviews with AI-powered practice sessions and instant feedback',
    keywords: [
      'interview preparation',
      'technical interview',
      'coding interview',
      'behavioral interview',
      'AI interview simulator',
      'mock interview',
      'career development'
    ],
    
    // Social media
    twitterHandle: '@{{ projectName | kebabCase }}',
    facebookAppId: process.env.FACEBOOK_APP_ID,
    
    // Structured data
    organization: {
      name: '{{ projectName | titleCase }}',
      url: 'https://{{ projectName | kebabCase }}.com',
      logo: 'https://{{ projectName | kebabCase }}.com/logo.png'
    }
  },

  // Internationalization
  i18n: {
    defaultLocale: 'en',
    locales: [
      { code: 'en', name: 'English', file: 'en.json' },
      { code: 'es', name: 'Español', file: 'es.json' },
      { code: 'fr', name: 'Français', file: 'fr.json' },
      { code: 'de', name: 'Deutsch', file: 'de.json' }
    ],
    
    // Date and number formatting
    dateFormat: {
      short: 'MM/DD/YYYY',
      long: 'MMMM D, YYYY',
      time: 'h:mm A'
    }
  }
})