name: cli
description: Generate Citty CLI applications
templates:
  - name: citty
    description: Complete Citty CLI application with TypeScript
    files:
      - "cli.ts"
      - "package.json"
      - "tsconfig.json"
    prompts:
      - name: cliName
        message: "CLI application name:"
        type: input
        default: my-cli
      - name: description
        message: "CLI description:"
        type: input
        default: "A CLI application built with Citty"