name: 'Reusable Setup Workflow'

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '18'
        type: string
      pnpm-version:
        description: 'PNPM version to use'
        required: false
        default: '9.12.0'
        type: string
      cache-dependency-path:
        description: 'Path to package-lock.json or pnpm-lock.yaml'
        required: false
        default: 'package-lock.json'
        type: string
      install-command:
        description: 'Custom install command'
        required: false
        default: 'pnpm install --frozen-lockfile'
        type: string
      fetch-depth:
        description: 'Number of commits to fetch'
        required: false
        default: 1
        type: number
      enable-corepack:
        description: 'Enable corepack for package manager setup'
        required: false
        default: true
        type: boolean
      working-directory:
        description: 'Working directory for all steps'
        required: false
        default: '.'
        type: string

jobs:
  setup:
    name: 'Setup Environment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Enable corepack
        if: inputs.enable-corepack
        run: npm i -fg corepack && corepack enable
        working-directory: ${{ inputs.working-directory }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ${{ inputs.working-directory }}/${{ inputs.cache-dependency-path }}

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Get PNPM store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        working-directory: ${{ inputs.working-directory }}

      - name: Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: ${{ inputs.install-command }}
        working-directory: ${{ inputs.working-directory }}