name: LaTeX Article Template
description: Generate LaTeX article documents with customizable sections
version: "1.0.0"
author: Unjucks LaTeX Generator
category: document

variables:
  title:
    type: string
    description: Document title
    required: true
    example: "Research Paper Title"
    
  author:
    type: string
    description: Document author(s)
    required: true
    example: "John Doe"
    
  output:
    type: string
    description: Output filename
    default: "document.tex"
    example: "my-paper.tex"
    
  fontSize:
    type: string
    description: Font size
    default: "12pt"
    enum: ["10pt", "11pt", "12pt"]
    
  paperSize:
    type: string
    description: Paper size
    default: "a4paper"
    enum: ["a4paper", "letterpaper", "legalpaper"]
    
  mathSupport:
    type: boolean
    description: Include math packages (amsmath, amsfonts, amssymb)
    default: true
    
  graphics:
    type: boolean
    description: Include graphicx package for images
    default: true
    
  abstract:
    type: string
    description: Document abstract
    required: false
    example: "This paper presents..."
    
  tableOfContents:
    type: boolean
    description: Include table of contents
    default: false
    
  introduction:
    type: string
    description: Introduction section content
    required: false
    
  mainContent:
    type: string
    description: Main content section
    required: false
    
  conclusion:
    type: string
    description: Conclusion section content
    required: false
    
  bibliography:
    type: boolean
    description: Include bibliography section
    default: false
    
  bibliographyStyle:
    type: string
    description: Bibliography style
    default: "plain"
    enum: ["plain", "abbrv", "alpha", "unsrt"]
    
  bibliographyFile:
    type: string
    description: Bibliography file name (without .bib extension)
    default: "references"
    
  customPackages:
    type: array
    description: Additional LaTeX packages to include
    items:
      type: string
    example: ["natbib", "babel"]
    
  marginLeft:
    type: string
    description: Left margin
    default: "2cm"
    
  marginRight:
    type: string
    description: Right margin
    default: "2cm"
    
  marginTop:
    type: string
    description: Top margin
    default: "2cm"
    
  marginBottom:
    type: string
    description: Bottom margin
    default: "2cm"
    
  date:
    type: string
    description: Document date
    default: "\\today"

templates:
  - name: document.tex.ejs
    description: Main LaTeX article template
  - name: references.bib.ejs.t
    description: BibTeX bibliography file (generated if references provided)
    conditional: references

examples:
  basic:
    title: "My Research Paper"
    author: "Jane Smith"
    abstract: "This paper explores innovative approaches to..."
    
  advanced:
    title: "Advanced LaTeX Document"
    author: "Dr. John Doe"
    fontSize: "11pt"
    mathSupport: true
    graphics: true
    abstract: "Comprehensive analysis of..."
    tableOfContents: true
    bibliography: true
    customPackages: ["natbib", "hyperref"]