---
to: <%= dest %>/references.bib
unless_exists: <%= !force %>
skip_if: <%= !references || references.length === 0 %>
---
<%# BibTeX Bibliography File %>
% Bibliography file generated for: <%= title %>
% Generated by Unjucks LaTeX MCP on <%= new Date().toISOString() %>

<% if (references && references.length > 0) { -%>
<% references.forEach(function(ref) { -%>
@<%= ref.type || 'article' %>{<%= ref.id %>,
  title={<%= ref.title %>},
  author={<%= ref.author %>},
<% if (ref.journal) { -%>
  journal={<%= ref.journal %>},
<% } -%>
<% if (ref.booktitle) { -%>
  booktitle={<%= ref.booktitle %>},
<% } -%>
<% if (ref.year) { -%>
  year={<%= ref.year %>},
<% } -%>
<% if (ref.volume) { -%>
  volume={<%= ref.volume %>},
<% } -%>
<% if (ref.number) { -%>
  number={<%= ref.number %>},
<% } -%>
<% if (ref.pages) { -%>
  pages={<%= ref.pages %>},
<% } -%>
<% if (ref.publisher) { -%>
  publisher={<%= ref.publisher %>},
<% } -%>
<% if (ref.doi) { -%>
  doi={<%= ref.doi %>},
<% } -%>
<% if (ref.url) { -%>
  url={<%= ref.url %>},
<% } -%>
<% if (ref.isbn) { -%>
  isbn={<%= ref.isbn %>},
<% } -%>
<% if (ref.note) { -%>
  note={<%= ref.note %>},
<% } -%>
}

<% }); -%>
<% } else { -%>
% No references provided
% Add your bibliography entries here
<% } -%>